name: Tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "news/**"
      - "*.md"
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "docs/**"
      - "news/**"
      - "*.md"

jobs:
  Testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        venv-backend: [virtualenv, venv, conda]

    steps:
      - uses: actions/checkout@v2
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
          prereleases: true
      - name: Set Variables
        id: set_variables
        run: |
          echo "::set-output name=PIP_CACHE::$(pip cache dir)"
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        if: matrix.venv-backend == 'conda'
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install packages
        run: python -m pip install -U nox .
      - name: Run Tests
        run: |
          export LD_PRELOAD=/lib/x86_64-linux-gnu/libgcc_s.so.1
          nox -s "test-${{ matrix.python-version }}(backend='${{ matrix.venv-backend }}')"
